language: php

# Use container-based infrastructure
sudo: false

php:
  - 7.2
  - 7.4
  - nightly

before_script:
  - mkdir -p /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d
  - composer self-update
  - composer install --prefer-source

matrix:
  allow_failures:
    - php: nightly
